server:
  port: 16001

logging:
  file:
    max-size: 100MB
    max-history: 7
  path: /houses/logs/housesManage

spring:
  datasource:
    name: db
    url: jdbc:mysql://127.0.0.1:3306/housesmanage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: wl2018!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapperLocations: classpath:mapping/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true
  params: count=countSql
